Validate Cargo.lock

diff --git a/.github/workflows/fmt-and-lint.yml b/.github/workflows/fmt-and-lint.yml
--- a/.github/workflows/fmt-and-lint.yml
+++ b/.github/workflows/fmt-and-lint.yml
@@ -29,6 +29,9 @@ jobs:
       - name: Build cache
         uses: ./.github/actions/build-cache
 
+      - name: Backup Cargo.lock
+        run: cp Cargo.lock Cargo.lock.bak
+
       - name: fmt check
         # Format checks aren't OS dependant.
         if: matrix.os == 'ubuntu-latest'
@@ -36,6 +39,14 @@ jobs:
 
       - name: clippy lint
         run: cargo clippy --all-targets --all-features -- --D warnings
+
+      - name: Validate Cargo.lock
+        run: |
+          if ! diff Cargo.lock Cargo.lock.bak; then
+            echo "Error: Cargo.lock has changed during the workflow. Ensure Cargo.lock is up-to-date and committed."
+            exit 1
+          fi
+        shell: bash
 
   wasm-lint:
     name: Wasm Lint Checks
